backend:
  name: git-gateway
  branch: main

media_folder: "static/img/uploads"
public_folder: "static/img/uploads"

collections:
  - name: "projects"
    label: "Projects"
    label_singular: "Project"
    folder: "content/projects"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "team"
    label: "Team Members"
    label_singular: "Team Member"
    folder: "content/team"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Position", name: "position", widget: "string" }
      - { label: "Bio", name: "bio", widget: "text" }
      - { label: "Photo", name: "photo", widget: "image" }

  - name: "settings"
    label: "Settings"
    files:
      - file: "content/settings/general.json"
        label: "General Settings"
        name: "general"
        fields:
          - { label: "Site Title", name: "site_title", widget: "string" }
          - { label: "Description", name: "description", widget: "text" }
          - { label: "Address", name: "address", widget: "string" }
          - { label: "Phone", name: "phone", widget: "string" }
          - { label: "WhatsApp", name: "whatsapp", widget: "string" }

  - name: "homepage"
    label: "الصفحة الرئيسية"
    files:
      - label: "بيانات الصفحة الرئيسية"
        name: "home"
        file: "content/home.json"
        fields:
          - { label: "العنوان الرئيسي", name: "hero_title", widget: "string" }
          - { label: "الوصف المختصر", name: "hero_subtitle", widget: "string" }
          - { label: "عن المؤسسة", name: "about_text", widget: "text" }
          - { label: "صورة رئيسية", name: "hero_image", widget: "image" }
          - label: "مشاريعنا"
            name: "projects"
            widget: "list"
            fields:
              - { label: "عنوان المشروع", name: "title", widget: "string" }
              - { label: "وصف المشروع", name: "description", widget: "string" }
              - { label: "صورة المشروع", name: "image", widget: "image" }
          - label: "قسم اتصل بنا"
            name: "contact"
            widget: "object"
            fields:
              - { label: "العنوان", name: "address", widget: "string" }
              - { label: "الهاتف", name: "phone", widget: "string" }
              - { label: "واتساب", name: "whatsapp", widget: "string" }
              - { label: "البريد الإلكتروني", name: "email", widget: "string" }
              - { label: "أوقات العمل", name: "working_hours", widget: "text" }
          - label: "الفوتر"
            name: "footer"
            widget: "object"
            fields:
              - { label: "العنوان الرئيسي", name: "title", widget: "string" }
              - { label: "الوصف", name: "description", widget: "text" }
              - { label: "رابط فيسبوك", name: "facebook", widget: "string" }
              - { label: "رابط إنستغرام", name: "instagram", widget: "string" }
              - { label: "رابط تويتر", name: "twitter", widget: "string" }
              - { label: "رابط واتساب", name: "whatsapp", widget: "string" }
              - { label: "حقوق الطبع", name: "copyright", widget: "string" }