backend:
  name: git-gateway
  branch: main

media_folder: "static/img/uploads"
public_folder: "/img/uploads"

collections:
  - name: "projects"
    label: "Projects"
    label_singular: "Project"
    folder: "content/projects"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "team"
    label: "Team Members"
    label_singular: "Team Member"
    folder: "content/team"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Position", name: "position", widget: "string" }
      - { label: "Bio", name: "bio", widget: "text" }
      - { label: "Photo", name: "photo", widget: "image" }

  - name: "settings"
    label: "Settings"
    files:
      - file: "content/settings/general.json"
        label: "General Settings"
        name: "general"
        fields:
          - { label: "Site Title", name: "site_title", widget: "string" }
          - { label: "Description", name: "description", widget: "text" }
          - { label: "Address", name: "address", widget: "string" }
          - { label: "Phone", name: "phone", widget: "string" }
          - { label: "WhatsApp", name: "whatsapp", widget: "string" }

  - name: "homepage"
    label: "الصفحة الرئيسية"
    files:
      - label: "بيانات الصفحة الرئيسية"
        name: "home"
        file: "content/home.json"
        fields:
          - { label: "العنوان الرئيسي", name: "hero_title", widget: "string" }
          - { label: "الوصف المختصر", name: "hero_subtitle", widget: "string" }
          - { label: "عن المؤسسة", name: "about_text", widget: "text" }
          - { label: "صورة رئيسية", name: "hero_image", widget: "image" }